spring.application.name=coreservices


#Postgresql Configuration
spring.datasource.driver-class-name=org.postgresql.Driver
#spring.datasource.url=jdbc:postgresql://localhost:5432/mth
spring.datasource.url=jdbc:postgresql://dpg-d8kendddt1ts73a057mg-a.oregon-postgres.render.com:5432/mth_c0ea
#spring.datasource.username=postgres
spring.datasource.username=postgres_user
#spring.datasource.password=sai1168167456
spring.datasource.password=Zik9KazppLxC3LpjM1V76HLvrGKvcaJv

#JPA Configuration
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#Port Number
server.port=8001